spring:
  application:
    name: roc-server-test

server:
  port: 8101

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/register/eureka/

